CREATE TABLE team (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE match (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  home_team_id INTEGER REFERENCES team(id),
  guest_team_id INTEGER REFERENCES team(id),
  date DATE NOT NULL
);

CREATE TABLE event (
  id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  match_id INTEGER REFERENCES match(id),
  team_id INTEGER REFERENCES team(id),
  type INTEGER NOT NULL,
  minutes INTEGER NOT NULL
);

